Add parser to the python api
cvc5/cvc5 pull request #10222
Opened 2023-12-13 15:27 UTC by daniel-larraz

2023-12-13 15:36 UTC, ajreynol requested changes
Can you also add the python equivalent of the examples: 
https://github.com/cvc5/cvc5/blob/main/examples/api/cpp/parser.cpp
https://github.com/cvc5/cvc5/blob/main/examples/api/cpp/parser_sym_manager.cpp
to the directory https://github.com/cvc5/cvc5/tree/main/examples/api/python?

@mudathirmahgoub this also is missing for Java.

2023-12-13 15:36 UTC, ajreynol commented on src/api/python/cvc5.pxd
> +        #void setStreamInput(InputLanguage lang, istream& input, const string& name) except +
You can delete this.

2023-12-13 20:27 UTC, daniel-larraz commented on src/api/python/cvc5.pxd
> +        #void setStreamInput(InputLanguage lang, istream& input, const string& name) except +
Done

2023-12-13 20:27 UTC, daniel-larraz commented
> Can you also add the python equivalent of the examples: https://github.com/cvc5/cvc5/blob/main/examples/api/cpp/parser.cpp https://github.com/cvc5/cvc5/blob/main/examples/api/cpp/parser_sym_manager.cpp to the directory https://github.com/cvc5/cvc5/tree/main/examples/api/python?
> 

Added

2023-12-14 14:50 UTC, ajreynol approved these changes

2023-12-14 15:08 UTC, merged