add laws of exoneration lemma to pow2
cvc5/cvc5 pull request #10237
Opened 2023-12-19 13:21 UTC by BergerZvika

2023-12-19 15:12 UTC, ajreynol requested changes
I think we should implement this as a rewrite (in https://github.com/cvc5/cvc5/blob/main/src/theory/arith/arith_rewriter.cpp).

If we do this, it should be the case that the regression simplifies to "false" during preprocessing.

2023-12-20 07:33 UTC, yoni206 commented
As Zvika pointed out to me offline, using a rewrite rule might be problematic.
Consider, for example, the formula `x<0 /\ pow2(x)*pow2(y)>0`.
This formula should be `unsat`, because [the way we defined `pow2` in `cvc5`](https://github.com/cvc5/cvc5/blob/a287aabdadbead4b5bbebaa4c57818cc4c3f207e/src/theory/arith/nl/pow2_solver.cpp#L156), `pow2(z)=0` whenever `z<0`.

But, if you rewrite `pow2(x)*pow2(y)` to `pow2(x+y)`, the resulting formula is `x<0 /\ pow2(x+y)>0`, and this formula is satisfiable.

Do you think there is a way of still using a rewrite for this, while avoiding this problem?

2023-12-20 10:29 UTC, yoni206 commented
Because it is meant to be an Int->Int operator, and with negative exponents
you no longer get an integer.
(BTW this how it is defined in `coq`
<https://coq.inria.fr/doc/V8.18.0/stdlib/Coq.Arith.PeanoNat.html#Nat.pow_neg_r>
also)

The other option is to have it be a partial function (like integer
division), but we preferred having a total function (Andy, I don't
remember, was there any other reason besides trying to avoid a partial
operator?).

Should we revisit this decision?


On Wed, Dec 20, 2023 at 12:06 PM Clark Barrett ***@***.***>
wrote:

> Why is pow2(x) = 0 when x < 0? This is not consistent with any usual
> interpretation of arithmetic.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvc5/cvc5/pull/10237#issuecomment-1864194880>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADAKGRAPAFRZGXNOLFIBBLLYKK2CLAVCNFSM6AAAAABA3FPDB6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRUGE4TIOBYGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-12-20 10:36 UTC, barrettcw commented
Hmm - I would prefer making it return a rational and having the usual semantics.  I don't think we have ever given an operator unnatural semantics like this in the past, and I don't think I want to start now.  Perhaps I'm missing something, but I don't see a good reason to limit pow2 to returning an integer.

2023-12-20 10:47 UTC, yoni206 commented
I can imagine cases where we would want to nest `pow2`s, that is, to
perform a `pow2` on the result of another `pow2` (for example, when
translating nested shifts from bit-vectors to integers). Taking this into
consideration, would we actually want to make this a `Rational -> Rational`
operator (and not `Int -> Rational`)?

On Wed, Dec 20, 2023 at 12:37 PM Clark Barrett ***@***.***>
wrote:

> Hmm - I would prefer making it return a rational and having the usual
> semantics. I don't think we have ever given an operator unnatural semantics
> like this in the past, and I don't think I want to start now. Perhaps I'm
> missing something, but I don't see a good reason to limit pow2 to returning
> an integer.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvc5/cvc5/pull/10237#issuecomment-1864242102>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADAKGRC7MAGNSSD534CN5ADYKK5VDAVCNFSM6AAAAABA3FPDB6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRUGI2DEMJQGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-12-20 11:04 UTC, barrettcw commented
In that case, sounds like Rational -> Rational would be the way to go.  You could always restrict it for a specific case by using an ite, and this forces you to think about what to do in the "undefined" case, which I think is a good thing.

2023-12-20 19:07 UTC, ajreynol commented
> As Zvika pointed out to me offline, using a rewrite rule might be problematic. Consider, for example, the formula `x<0 /\ pow2(x)*pow2(y)>0`. This formula should be `unsat`, because [the way we defined `pow2` in `cvc5`](https://github.com/cvc5/cvc5/blob/a287aabdadbead4b5bbebaa4c57818cc4c3f207e/src/theory/arith/nl/pow2_solver.cpp#L156), `pow2(z)=0` whenever `z<0`.
> 
> But, if you rewrite `pow2(x)*pow2(y)` to `pow2(x+y)`, the resulting formula is `x<0 /\ pow2(x+y)>0`, and this formula is satisfiable.
> 
> Do you think there is a way of still using a rewrite for this, while avoiding this problem?

FYI, my original suggestion was the opposite, `pow2(x+y)` should become `pow2(x)*pow2(y)`.

However, I do think this needs more thought in regards to the type of `pow2`.

2023-12-25 03:13 UTC, yoni206 commented
Based on the discussion above: closing the PR for now. Let's get back to this after the type of `pow2` is changed.

2025-04-22 07:34 UTC, yoni206 commented
After some discussion with @mpreiner , it seems like there is a reasonable interpretation according to which pow2(k)=0 whenever k<0, when `pow2 : Int -> Int`.
For a natural number n, `2^{-n}=(1 div (2^n))=0`.

My proposal is to continue with having `pow2` as an operator from Int to Int, with this semantics, and keeping the extension to rational exponentiation to future work.

@barrettcw is this acceptable?

2025-04-22 13:16 UTC, barrettcw commented
I see - yes I suppose this is reasonable.  We should document this carefully.

2025-04-22 16:05 UTC, closed without merging