Add special rule for injective functions for bag.map terms
cvc5/cvc5 pull request #10306
Opened 2024-01-25 22:21 UTC by mudathirmahgoub

2024-01-25 22:35 UTC, ajreynol approved these changes

2024-01-30 21:27 UTC, ajreynol requested changes

2024-01-30 21:27 UTC, ajreynol commented on src/theory/bags/inference_generator.h
> +   * @return an inference that represents the following implication
```suggestion
   * @return an inference that represents the following conjunction
```

2024-01-30 21:54 UTC, mudathirmahgoub commented on src/theory/bags/solver_state.cpp
> +  TypeNode domainType = f.getType().getArgTypes()[0];
Done

2024-01-31 14:30 UTC, ajreynol approved these changes

2024-01-31 14:30 UTC, merged