Separate free variable cache utility from sygus enumerator
cvc5/cvc5 pull request #10358
Opened 2024-02-08 15:43 UTC by ajreynol

This is work towards improving the internal interface of sygus enumerator.

This makes it so that we can enumerate shapes (terms with free variables) without having a sygus term database.

2024-02-14 20:12 UTC, abdoo8080 requested changes

2024-02-14 20:12 UTC, abdoo8080 commented on src/theory/quantifiers/sygus/term_database_sygus.cpp
> +  // It should be a free variable allocated with useSygusType = false.
```suggestion
  // It should be a free variable allocated by this class.
```

2024-02-15 15:21 UTC, abdoo8080 approved these changes
LGTM! Please address the last comment about the assertion before merging.

2024-02-15 15:42 UTC, ajreynol commented on src/expr/free_var_cache.cpp
> +  }
This code is intentionally like this to be safe, since this is not a critical failure.  The current code returns 0 without segfaulting in production.

2024-02-15 16:33 UTC, merged