c++ api: Expose TermManager to the API.
cvc5/cvc5 pull request #10426
Opened 2024-02-24 01:50 UTC by aniemetz

This introduces a TermManager object, which will, in the future, be the sole object responsible for handling/managing terms and sorts. For now, all corresponding functions in `cvc5::Solver` are marked as deprecated, as is constructor `cvc5::Solver::Solver()`, since in the future a solver instance must be constructed from a term manager instance. Currently, we maintain a static thread_local term manager instance to not break the API and continue providing constructor `cvc5::Solver::Solver()`.

Note that this already converts all C++ unit tests to use the TermManager except for a single test `getStatistics()` in `test/unit/api/cpp/solver_black.cpp`. Statistics handling is currently still maintained on the solver level. The statistics we maintain, however, concern terms only and will eventually be refactored to be tracked in the NodeManager.

Further note that the Java API will be refactored in a separate PR.

2024-03-04 18:04 UTC, ajreynol requested changes

2024-03-04 18:04 UTC, ajreynol commented on src/parser/parser_state.cpp
> +  Term expr = d_solver->getTermManager().mkConst(type, name);
This is relatively performance intensive code, can you cache a term manager pointer in `ParserState` in this class and use it here?

2024-03-04 18:04 UTC, ajreynol commented on src/parser/smt2/smt2_state.cpp
> +  TermManager& tm = d_solver->getTermManager();
Ditto, use the cached term manager in this class (which inherits from ParserState).

2024-03-06 21:20 UTC, mpreiner approved these changes

2024-03-08 18:37 UTC, ajreynol approved these changes
LGTM

2024-03-08 19:39 UTC, merged