Adds the Carcara proof checker infrastructure
cvc5/cvc5 pull request #10529
Opened 2024-03-20 23:46 UTC by vinisilvag

This PR adds the [Carcara](https://github.com/ufmg-smite/carcara) infrastructure.

Future PR's will add the updates that will allow run Carcara in the regression tests and verify proofs in the Alethe format.

2024-03-27 14:02 UTC, HanielB requested changes

2024-03-27 14:02 UTC, HanielB commented on test/regress/cli/CMakeLists.txt
> +  alethe
For now remove this so that the tester cannot be used via cmake. Only when the support for Alethe is stabilized in main we will enable this.

2024-03-27 14:02 UTC, HanielB commented on test/regress/cli/run_regression.py
> +
Delete this part since it is no longer necessary.

2024-03-27 14:02 UTC, HanielB commented on test/regress/cli/run_regression.py
> +                "--proof-granularity=theory-rewrite"
this option is no longer necessary since setting the format for Alethe automatically sets the granularity to this level.

2024-04-10 13:06 UTC, HanielB approved these changes

2024-04-10 22:33 UTC, vinisilvag commented
> Can you rename `get-alethe-checker` to `get-carcara-checker`?

Sure!

2024-04-11 14:46 UTC, ajreynol requested changes

2024-04-11 14:46 UTC, ajreynol commented on contrib/get-carcara-checker
> +cat << EOF > $BASE_DIR/bin/cvc5-alethe-check.sh
These generated scripts should also update to use the name "carcara", not "alethe".

2024-08-20 16:07 UTC, ajreynol approved these changes

2024-08-21 20:14 UTC, merged