c++ API: Refactor statistics handling. @aniemetz
cvc5/cvc5 pull request #10530
Opened 2024-03-21 02:01 UTC by aniemetz

This moves term statistics collection from Solver to TermManager.
TermManager and Solver now both provide `getStatistics()`, the former
captures API level term statistics, the latter internal solver
statistics.

This builds on top of #10528.

2024-03-21 15:53 UTC, ajreynol requested changes
Can you rebase? 
Also, can you comment on whether there are any expected behavior changes when using CLI?

2024-03-21 15:53 UTC, ajreynol commented on include/cvc5/cvc5.h
> +  /** The statistics registry (indepent from any Solver's registry. */
```suggestion
  /** The statistics registry (independent from any Solver's registry). */
```

2024-03-21 16:07 UTC, aniemetz commented
> Also, can you comment on whether there are any expected behavior changes when using CLI?

As mentioned in the description, term related statistics are now captured in the TermManager statistics and not included in the Solver statistics anymore (everything we capture with `increment_*_stats).

2024-03-21 16:24 UTC, ajreynol commented
So we don't print TermManager statistics via CLI using `--stat-internal`?  If not, should we modify `src/main/` to do this?

2024-03-21 16:32 UTC, aniemetz commented
Good point, I guess so?

2024-03-21 16:33 UTC, aniemetz commented
Wait, shouldn't this already be taken care of via `CommandExecutor::printStatisticsSafe()`?

2024-03-21 20:37 UTC, aniemetz commented
Addressed.

2024-04-01 16:56 UTC, ajreynol approved these changes

2024-04-01 21:12 UTC, merged