Expose DSL Proof Rules.
cvc5/cvc5 pull request #10568
Opened 2024-03-31 05:17 UTC by abdoo8080

This PR implements one approach to exposing DSL Proof rules to the user: by making the DSL rule enum public.

2024-04-10 21:14 UTC, ajreynol commented
We will need to merge https://github.com/cvc5/cvc5/pull/10614 first.

2024-04-15 14:23 UTC, ajreynol requested changes
How about `ProofRewriteRule`?

Feel free to rename other internal names in this PR if this conflicts.

Also, I think we should put the new enum inside of `cvc5_proof_rule.h`, since both pertain to proofs. Is this possible?  What do you think?

2024-04-15 15:46 UTC, abdoo8080 commented
> How about `ProofRewriteRule`?
> 
> Feel free to rename other internal names in this PR if this conflicts.
> 
> Also, I think we should put the new enum inside of `cvc5_proof_rule.h`, since both pertain to proofs. Is this possible? What do you think?

Works for me! This name does not have any conflicts either, `ProofRewriteRule` vs. `RewriteProofRule` :)

It's possible to move the enums in this file to `cvc5_proof_rule.h`. I don't have a strong opinion, but I prefer to have them separated. There are minor benefits to keep them separate: less files to recompile and ease of formatting and documentation.

2024-04-15 16:22 UTC, ajreynol commented
I think we should probably prioritize user convenience in this case. I think it is better for a user have access to all proof rules (core or rewrite) in one header file.

2024-04-17 16:55 UTC, ajreynol requested changes

2024-04-17 16:55 UTC, ajreynol commented on include/cvc5/cvc5_proof_rule.h
> +  EVALUE(ARITH_PLUS_ZERO),
This is somewhat minor, is it possible to generate a one line comment for each rule here?
Something like
/** Auto-generated from RARE rule arith-plus-zero */

2024-04-18 14:40 UTC, ajreynol approved these changes
LGTM

2024-04-18 15:09 UTC, merged