Support erasing substitutions
cvc5/cvc5 pull request #10690
Opened 2024-04-25 18:54 UTC by ajreynol

This will be used in a forthcoming new method for minimizing explanations from theory lemmas.

2024-05-02 17:02 UTC, HanielB requested changes

2024-05-02 17:02 UTC, HanielB commented on src/theory/substitutions.cpp
> +  // the range of other d_substitutions can be out of sync
please expand, maybe give an example

2024-05-06 13:48 UTC, ajreynol commented on src/theory/substitutions.h
> +   * add { x -> a }, then we may update the entry for y to { y -> f(a) }.
I think "compression" is the right word since its compressing two substitutions into one. "updating" is more vague.

2024-05-06 13:49 UTC, ajreynol commented on src/theory/substitutions.h
> +   * x may be substituted into the range of the substitution in this class.
I will clarify the doc.

2024-05-06 14:35 UTC, HanielB commented on src/theory/substitutions.h
> +   * add { x -> a }, then we may update the entry for y to { y -> f(a) }.
Hum, but would x -> a be kept? This was not clear from the documentation.

2024-05-06 19:43 UTC, HanielB commented on src/theory/substitutions.h
> +   * add { x -> a }, then we may update the entry for y to { y -> f(a) }.
I see. Can you add that `x -> a` is kept and that the only change is to update the entry for `y`?

2024-05-06 19:44 UTC, HanielB approved these changes

2024-05-07 16:08 UTC, merged