Add conflict processor module
cvc5/cvc5 pull request #10738
Opened 2024-05-08 13:37 UTC by ajreynol

This module can be used to minimize explanations of theory lemmas and conflicts. In practice, around 30% of lemmas can be minimized using this module.  This leads to significant improvements in performance in some industrial benchmarks.

A followup PR will optionally enable this technique (disabled by default, as it gives mixed performance on SMT-LIB).

Another use case will be for automatic proof reconstruction, as this module can infer proofs for theory lemmas in a generic way.

2024-07-03 13:01 UTC, HanielB requested changes

2024-07-03 13:44 UTC, ajreynol commented on src/theory/conflict_processor.h
> +   *    (= y 0) returns false.
Yes, its a heuristic.

2024-07-03 13:45 UTC, ajreynol commented on src/theory/conflict_processor.h
> +   *    (= y 0) returns false.
FYI, I did start to write a more general method but quickly realized it was too heavy handed.  This is something to consider separately though.

2024-07-03 13:46 UTC, ajreynol commented on src/theory/conflict_processor.h
> +  bool d_useExtRewriter;
Ah, somehow this was lost in merge, will add.

2024-07-17 19:31 UTC, HanielB commented on src/theory/conflict_processor.cpp
> +      if (k == Kind::OR || k == Kind::IMPLIES)
Right, but won't this be only at the initial level, and not at every recursive case, which this loop is going through?

2024-07-17 19:34 UTC, ajreynol commented on src/theory/conflict_processor.cpp
> +      if (k == Kind::OR || k == Kind::IMPLIES)
you could also have `(or (or A B (or C D) E) F)` in theory.

2024-07-17 19:36 UTC, HanielB approved these changes

2024-07-17 19:36 UTC, HanielB commented on src/theory/conflict_processor.h
> +   * @return A trust node for a lemma that implies lem.
ping

2024-07-18 14:53 UTC, merged