Allow theories to occur in a logic name in any order
cvc5/cvc5 pull request #11207
Opened 2024-09-17 14:48 UTC by daniel-larraz

It also checks that only one arithmetic theory is provided.

2024-09-25 00:20 UTC, ajreynol requested changes
Isn't there a more general issue: is `BVBVBV` a valid logic now?

2024-09-25 00:20 UTC, ajreynol commented on src/theory/logic_info.cpp
> +          if (*arithmetic_theory != '\0')
Our guidelines require brackets `if (...) { ... }` not `if() ...`.

2024-09-30 19:04 UTC, daniel-larraz commented
> Isn't there a more general issue: is `BVBVBV` a valid logic now?

After the change, `BVBVBV` is an accepted logic, which is interpreted as simply `BV`. I was leaning towards being more flexible and allowing any combination that doesn't have an ambiguous interpretation. However, I can modify the code to reject multiple instances of the same logic component if needed.

2024-09-30 19:24 UTC, ajreynol commented
I think we should probably reject duplicates, yes.

2024-10-02 16:11 UTC, daniel-larraz commented on src/theory/logic_info.h
> +  void checkDuplicateTheory(theory::TheoryId theory, const char* id);
Done

2024-10-08 14:44 UTC, ajreynol approved these changes

2024-10-08 15:20 UTC, merged