[proofs] [alethe] Update doc, remove experimental option
cvc5/cvc5 pull request #11210
Opened 2024-09-17 23:04 UTC by HanielB

2024-09-24 15:32 UTC, ajreynol requested changes
This is pending experiments.

2024-09-24 16:58 UTC, HanielB commented
What experiments do you have in mind?

2024-09-24 16:59 UTC, ajreynol commented
Running some sanity checks over SMT-LIB for the printer now, it would be good to have a apples-to-apples comparison of CPC+Ethos vs. Alethe+Carcara on all logics fully supported by Alethe+Carcara.

2024-09-24 19:46 UTC, HanielB commented
I'll kick off an SMT-LIB run in AUFBVLIRADT (or something like that) that should include what is supported by cvc5+Carcara, it'll be a good sanity check indeed. Comparing with CPC+Ethos I think would be nice also but less priority, so I'd rather leave for later. What do you think?

2024-09-24 19:50 UTC, ajreynol commented
That's fine but it might make it harder to interpret the results, what would be ideal is to know what is the overhead of using Alethe vs. CPC.

2024-09-24 20:56 UTC, HanielB commented
I agree it would be nice to compare like this, but I don't think this should be a criterion to remove the experimental flag.

2024-09-24 21:03 UTC, HanielB commented on docs/proofs/output_alethe.rst
> +download and install the Carcara checker's version with full support for cvc5
It is not HEAD, unfortunately. I have to merge a number of updates (for bit-vectors and datatypes, mostly) into the main of Carcara and have not gotten the time yet.

2024-09-26 20:45 UTC, HanielB commented
Running on SMT-LIB on logics (with or without quantifiers) with AUFBVDTLIRA, 300s, 8gb, comparing against `main` without proofs, there are no disagreements and no more errors, the impact is only in performance:
```
                       status  total  solved    sat  unsat   best  timeout  memout  error  uniq  disagr  time_cpu     memory
benchmark   config                                                                                                          
ABV         main/          ok   4975     107     17     90    107        3       0      0     0       0     908.3    14820.6
            pf-alethe/     ok   4975     108     17     91     81        7       0      0     1       0    2461.4    43835.7
ALIA        main/          ok   3098     108     16     92    104        3       0      0     0       0     936.8     9889.8
            pf-alethe/     ok   3098     108     16     92     66        3       0      0     0       0     956.1    13091.1
AUFBV       main/          ee   1523     190      0    190    188      154       4    156    47       0   63898.7   424650.3
            pf-alethe/     ee   1523     147      0    147      6      278      81    156     4       0  121845.9  1821400.0
AUFBVDTLIA  main/          ok   1683     392      4    388    392      701       3      0     4       0  210953.6   413324.0
            pf-alethe/     ok   1683     390      4    386    296      696      10      0     2       0  211511.5  1039604.3
AUFDTLIA    main/          ok    795     697      3    694    697       35       0      0     0       0   10570.4    17333.8
            pf-alethe/     ok    795     697      3    694    614       35       0      0     0       0   11146.1    31790.9
AUFDTLIRA   main/          ok  11043    9904      0   9904   9900       59       0      0     1       0   18798.3    60003.1
            pf-alethe/     ok  11043    9903      0   9903   6025       60       0      0     0       0   19515.2   143978.2
AUFLIA      main/          ok   3327    2037     28   2009   2036      421       3      0     0       0  130627.0   358107.9
            pf-alethe/     ok   3327    2037     28   2009   1579      400      24      0     0       0  128818.0   816289.2
AUFLIRA     main/          ok  20011   19743      0  19743  19741      112       0      0     0       0   36607.7    90725.0
            pf-alethe/     ok  20011   19743      0  19743  17467      125     192      0     0       0   80192.1  2454637.7
BV          main/          ok   6185    5651    446   5205   5634      534       0      0   484       0  166605.7   291634.8
            pf-alethe/     ok   6185    5169    321   4848   4051     1008      48      0     2       0  321978.0  2440769.5
LIA         main/          ok    416     416    150    266    415        0       0      0     0       0      78.5     1341.9
            pf-alethe/     ok    416     416    150    266    258        0       0      0     0       0     102.4     2666.4
LRA         main/          ok   2439    1915    597   1318   1911      524       0      0     1       0  162871.9    64288.9
            pf-alethe/     ok   2439    1914    596   1318    994      528       0      0     0       0  163801.1   159013.7
QF_ABV      main/          ok  15148   14429   9922   4507  13275      702      17      0   272       0  298389.2   922279.0
            pf-alethe/     ok  15148   14263   9866   4397   8646      821      98      0   106       0  356058.9  3867198.0
QF_ALIA     main/          ok    176     111     40     71     95       65       0      0     6       0   23418.9    40026.5
            pf-alethe/     ok    176     105     35     70     39       71       0      0     0       0   24354.5    73997.1
QF_ANIA     main/          ok    157     117    103     14    108       40       0      0     2       0   14626.5    15234.1
            pf-alethe/     ok    157     116    103     13     76       42       0      0     1       0   15883.7    38589.4
QF_AUFBV    main/          ok     75      43     12     31     43       22      10      0     2       0    7877.0   124768.2
            pf-alethe/     ok     75      42     11     31      4       19      15      0     1       0    7936.5   180401.0
QF_AUFLIA   main/          ok   1303    1303    543    760   1252        0       0      0     3       0    2006.9    13284.2
            pf-alethe/     ok   1303    1300    543    757    839        9       0      1     0       0    6419.2   120020.3
QF_AX       main/          ok    551     551    272    279    551        0       0      0     2       0     983.0     2903.9
            pf-alethe/     ok    551     549    272    277    275        2       0      0     0       0    2583.8    69226.0
QF_BV       main/          ok  46191   43338  17207  26131  43016     2756      97      0  7059       0 1170330.7  5482827.1
            pf-alethe/     ok  46191   36387  14103  22284  14117     9696    2197      0   108       0 3207987.4 47494760.4
QF_DT       main/          ok   8700    8253   3648   4605   8243      447       0      0    11       0  142534.4   254007.9
            pf-alethe/     ok   8700    8246   3647   4599   8063      466       0      0     4       0  147974.8  2401720.6
QF_IDL      main/          ok   2528    1597    902    695   1571      921      10      0   183       0  325240.4   865592.9
            pf-alethe/     ok   2528    1420    788    632    194     1103      75      0     6       0  384326.6  2440207.8
QF_LIA      main/          ok  13306    9784   6822   2962   9566     3460      62      0   271       0 1149785.6  4189711.4
            pf-alethe/     ok  13306    9552   6733   2819   6503     3876     116      0    39       0 1253326.8  8094056.9
QF_LIRA     main/          ok      7       5      1      4      5        2       0      0     0       0     628.1     1418.9
            pf-alethe/     ok      7       5      1      4      0        2       1      0     0       0     970.1    21391.9
QF_LRA      main/          ok   1753    1514    890    624   1474      239       0      0    37       0  108611.6   206982.1
            pf-alethe/     ok   1753    1487    878    609    654      289       1      0    10       0  130425.8   727045.5
QF_RDL      main/          ok    255     202    101    101    200       53       0      0     5       0   20785.0    21207.7
            pf-alethe/     ok    255     197    101     96     13       62       0      0     0       0   25639.5   130780.7
QF_UF       main/          ok   7503    7493   3142   4351   7395       10       0      0     8       0    9066.6    56082.6
            pf-alethe/     ok   7503    7485   3142   4343   1932       26       1      0     0       0   32173.0   598466.6
QF_UFBV     main/          ok   1510    1318    710    608   1229      127      65      0    54       0   59079.3   938715.2
            pf-alethe/     ok   1510    1287    683    604    179      121     131      0    23       0   68372.2  1744452.2
QF_UFBVDT   main/          ok     76      33     28      5     33       14      29      0    16       0    8044.1   328275.4
            pf-alethe/     ok     76      17     15      2      0        5      54      0     0       0    7432.6   513035.7
QF_UFDT     main/          ok    203     101     78     23     85      102       0      0    15       0   41008.7    62322.1
            pf-alethe/     ok    203      88     77     11     26      117       0      0     2       0   43200.7   207672.9
QF_UFDTLIA  main/          ok     76      30     23      7     23       46       0      0     1       0   14811.3    30306.5
            pf-alethe/     ok     76      34     28      6     13       41       1      0     5       0   14691.7    71501.5
QF_UFDTLIRA main/          ok    146     146     80     66    146        0       0      0     0       0       0.0      281.7
            pf-alethe/     ok    146     146     80     66    146        0       0      0     0       0       0.0      372.9
QF_UFIDL    main/          ok    62 [...]

2024-09-27 14:27 UTC, ajreynol commented
This looks good to me, @hansjoergschurr did you have an open question to address?

2024-09-27 14:27 UTC, ajreynol approved these changes

2024-09-27 15:16 UTC, HanielB commented on docs/proofs/output_alethe.rst
> +download and install the Carcara checker's version with full support for cvc5
I think it can wait, since we are using the script and this is explained. But I'll try to address this ASAP.

2024-09-27 22:12 UTC, merged