[proofs] [alethe] Generalize ALPHA_EQUIV translation
cvc5/cvc5 pull request #11236
Opened 2024-09-28 14:41 UTC by HanielB

In some cases the renaming used in the ALPHA_EQUIV rule in cvc5 is not directly valid via a `bind` rule in Alethe, since entries added to the context are used to generate a substitution using a cumulative strategy. This PR addresses this issue by breaking down the renaming into more than one `bind` step when this happens. The translation in the Alethe post-processor is generalized to account for both the regular and this special case.

2025-01-22 23:25 UTC, HanielB commented
The changes in this PR have been updated to have a simpler solution for the name clashing, following the solution from #11237.

2025-01-24 00:51 UTC, Lachnitt requested changes
I left one comment asking for a small documentation change and one minor code change. Everything else looks good.

2025-01-24 00:51 UTC, Lachnitt commented on src/proof/alethe/alethe_post_processor.cpp
> -  std::vector<Node> new_args = std::vector<Node>();
This should be changed in its own PR if necessary.

2025-01-24 00:51 UTC, Lachnitt commented on src/proof/alethe/alethe_post_processor.cpp
> +    // When F := (forall ((y1 A1) ... (yk Ak)) G) and sigma is the substitution
The structure is a little confusing. Right now it seems that you say:

The general form is this. The result is always as follows.
Unless Case B (sigma is id) applies, then result is as follows.

Another form is this. It represents a case where XY. Then, the result is as follows.

2025-01-24 13:24 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.cpp
> -  std::vector<Node> new_args = std::vector<Node>();
Removed.

2025-01-24 13:25 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.cpp
> +    // When F := (forall ((y1 A1) ... (yk Ak)) G) and sigma is the substitution
I've reorganized the documentation so that it first lists the special cases then the unrestricted case. PTAL

2025-01-27 22:45 UTC, Lachnitt commented on src/proof/alethe/alethe_post_processor.cpp
>        for (size_t i = 0, size = res[0][0].getNumChildren(); i < size; ++i)
This would not work for

```
res[0][0] = ((?v0 A) (?v1 B)) 
res[1][0] = ((?v1 A) (?v2 B))
```
Or am I overlooking something?

2025-01-27 22:53 UTC, Lachnitt commented
See my comment above. I do think we need to also check for rhs names. If I extend the code like this (there is surely a better way):

```
3820       bool allSame = true;
3821       std::vector<std::string> lhsNames;
3822       std::vector<std::string> rhsNames;
3823       bool hasClash = false;
3824       for (size_t i = 0, size = res[0][0].getNumChildren(); i < size; ++i)
3825       {
3826         Node v0 = res[0][0][i], v1 = res[1][0][i];
3827         if ((std::find(lhsNames.begin(), lhsNames.end(), v1.getName())
3828             != lhsNames.end()) || (std::find(rhsNames.begin(), rhsNames.end(), v0.getName())
3829             != rhsNames.end()))
3830         {
3831           hasClash = true;
3832           allSame = false;
3833         }
3834         lhsNames.push_back(v0.getName());
3835         rhsNames.push_back(v1.getName());
3836         allSame = allSame && v0 == v1;
3837       }
```

I have a benchmark that gets corrected. Cannot upload here will sent on Zulip

2025-01-27 23:29 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.cpp
>        for (size_t i = 0, size = res[0][0].getNumChildren(); i < size; ++i)
You're right, it was a bug. Fixed and added a regression.

2025-02-11 23:25 UTC, Lachnitt approved these changes
Thanks for improving the documentation. This makes sense now.

2025-02-12 12:39 UTC, HanielB commented
Any further comments @hansjoergschurr?

2025-04-01 22:03 UTC, Lachnitt commented
@hansjoergschurr can we merge this?

2025-04-11 17:57 UTC, merged