[proofs] [alethe] Improve error flagging to catch unsupported types
cvc5/cvc5 pull request #11235
Opened 2024-09-27 20:58 UTC by HanielB

This allows cvc5 to realize it is an unsupported fragment in Alethe also when the problem contains only variables of unsupported theories, which requires us to look at their type. As a consequence, we can re-enable a few regressions.

This fixes the nightlies, where a build with Cocoa (which is not tested in CI) was generating proofs without FF operators but with FF variables.

2024-10-02 15:52 UTC, ajreynol requested changes

2024-10-02 15:52 UTC, ajreynol commented on src/proof/alethe/alethe_node_converter.cpp
> +              case TypeConstant::BUILTIN_OPERATOR_TYPE:
What does this correspond to?

2024-10-09 01:16 UTC, HanielB commented on src/proof/alethe/alethe_node_converter.cpp
> +              case TypeConstant::BUILTIN_OPERATOR_TYPE:
Yeah, I think this should not be here.

2024-10-14 21:05 UTC, ajreynol approved these changes

2024-10-14 21:57 UTC, merged