Add proof reconstruction for ProofRewriteRule::MACRO_QUANT_VAR_ELIM_EQ
cvc5/cvc5 pull request #11323
Opened 2024-10-30 19:15 UTC by ajreynol

Handles nearly all cases of this rule, although 4/126 are instances of a more complex rewrite ("datatype tester expansion") which need separate treatment.

2024-11-07 09:07 UTC, abdoo8080 requested changes
Thanks for the PR! Looking back at the documentation for `MACRO_QUANT_VAR_ELIM_EQ`, I think its formula should be:
```
   *   \forall Y_1 x Y_2.\> F = \forall Y_1 Y_2.\> F \{ x \mapsto t \}
```

2024-11-07 14:23 UTC, ajreynol commented on src/theory/quantifiers/quantifiers_rewriter.cpp
> +    lits.emplace_back(pol ? n : n.notNode());
No, negate implicitly does double negation elimination, which complicates things.

Lits is just a way to remember what the literal was that justified the substitution, e.g.
```
vars = {x}
subs = {y-z}
lits = {x+z=y}

2024-11-07 15:25 UTC, ajreynol commented on proofs/eo/cpc/rules/Quantifiers.eo
> +  (($mk_quant_var_elim_eq x (not (= x t)))        ($mk_quant_var_elim_eq_subs x t false))
Done

2024-11-07 15:26 UTC, ajreynol commented on src/rewriter/basic_rewrite_rcons.cpp
> +  }
No, these are two different things that have to be performed if the equality literal is different from the solved literal.

2024-11-08 19:40 UTC, ajreynol commented on src/rewriter/basic_rewrite_rcons.cpp
> +  }
I've deleted it now.

2024-11-08 20:01 UTC, abdoo8080 approved these changes

2024-11-09 15:45 UTC, merged