Remove NodeBuilder constructors with implicit NodeManager
cvc5/cvc5 pull request #11392
Opened 2024-11-26 21:08 UTC by daniel-larraz

This change introduces some calls to `NodeManager::currentNM()`, which will be removed in a follow-up PR.

2024-12-04 16:00 UTC, ajreynol requested changes

2024-12-04 16:35 UTC, daniel-larraz commented on src/preprocessing/passes/bv_to_bool.cpp
> +      NodeBuilder builder(current.getNodeManager(), current.getKind());
Fixed.

2024-12-04 16:35 UTC, daniel-larraz commented on src/preprocessing/passes/foreign_theory_rewrite.cpp
> +  NodeBuilder builder(originalNode.getNodeManager(), k);
The issue is that `ForeignTheoryRewriter::reconstructNode` is a static method.

2024-12-04 16:36 UTC, daniel-larraz commented on src/theory/arith/linear/arith_static_learner.cpp
> +  NodeManager* nm = n.getNodeManager();
If this is the only change blocking this PR, I'd rather merge it now and apply the change after PR #11382 is merged.

2024-12-09 19:35 UTC, ajreynol approved these changes

2024-12-09 21:55 UTC, merged