Add infrastructure to translate THEORY_LEMMAS that have a ProofRewriteRule + two distinct rules
cvc5/cvc5 pull request #11399
Opened 2024-12-02 20:56 UTC by Lachnitt

There are some rewrite rules that cannot be expressed in RARE (also called ad-hoc rules). They should be translated to existing Alethe rules whenever possible.

This PR adds a separate function to the callback for this which is cleaner then doing it in the main update function because of too much indentation.

It also translates the DISTINCT_ELIM and DISTINCT_CARD_CONFLICT rules.

2024-12-03 14:50 UTC, HanielB requested changes

2025-04-25 20:52 UTC, Lachnitt commented on src/proof/alethe/alethe_post_processor.cpp
> +      }
Sorry this PR was not ready yet, I updated it do translate to a rewrite rule.

2025-05-02 20:32 UTC, HanielB requested changes

2025-05-02 20:32 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.cpp
> +      if (rewriter::getRewriteRule(args[0], di))
This rule is only generated internally when `rewriter::getRewriteRule` is expected to succeed, so we should translate this rule under this assumption. There is no need to treat the case where a hole would have to be produced, because this should be seen as a cvc5 error.

2025-05-02 20:32 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.h
> +                                           bool& continueUpdate,
remove this argument, it is not needed

2025-05-02 20:57 UTC, Lachnitt commented on src/proof/alethe/alethe_post_processor.cpp
> +      if (rewriter::getRewriteRule(args[0], di))
Makes total sense, ~~I'll add an Assertion though just in case.~~

2025-05-07 11:53 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.h
> +   * @param cdp The proof to add to
just the `di` argument missing, as well as the return value

2025-05-12 13:55 UTC, HanielB commented on src/proof/alethe/alethe_post_processor.h
> +   * @param did The id of the ProofRewriteRule the THEORY_REWRITE step expresses,
did -> di

2025-05-19 18:56 UTC, HanielB approved these changes

2025-05-19 19:13 UTC, merged