Add proof elaboration for diamonds preprocessing
cvc5/cvc5 pull request #11447
Opened 2024-12-13 14:37 UTC by ajreynol

One new RARE rule is added for this purpose.

Otherwise the elaboration involves AND_INTRO, TRANS, SCOPE, EQ_RESOLVE.

2025-01-23 03:36 UTC, Lachnitt commented on src/theory/uf/diamonds_proof_generator.cpp
> +  std::vector<Node> children(fact.begin(), fact.end());
It's a little confusing that `children` is initialized here with `{antec,conc}` just to be replaced by `{antec[0],conc}` before being used. I think the comment I describe above might resolve this.

2025-01-23 03:54 UTC, Lachnitt requested changes
I have a hard time understanding this. I think there need to be more comments. 
Can antec have only two children? Can every child of antec only have two children? I.e.,

fact: (=> (or antec[0] antec[1]) (= conc[0] conc[1]))
antec[0]: (and (= antec[0][0][0] antec[0][0][1]) (= antec[0][1][0] antec[0][1][1]))
antec[1]: (and (= antec[1][0][0] antec[1][0][1]) (= antec[1][1][0] antec[1][1][1]))

Why is children initialized as {antec,concl} but then before using it changed to {antec[0],concl}?

2025-01-29 22:48 UTC, ajreynol commented
I've added comments to explain the proof steps, indeed the code is very hard coded to a specific pattern.

2025-02-11 23:23 UTC, Lachnitt approved these changes
Thanks for the changes, this is clear now.

2025-02-12 16:21 UTC, merged