Add new interface for parsing inputs
cvc5/cvc5 pull request #6544
Opened 2021-05-14 23:24 UTC by 4tXJ7f

This commit introduces the `InputParser` class, which is now the main
interface for retrieving commands and expressions from parsers for a
given input. The idea is that a `Parser` can be used to parse multiple
inputs (e.g., in the interactive shell) and that the
commands/expressions in each input can be retrieved using an
`InputParser`.

2021-05-18 09:22 UTC, nafur requested changes
Some suggestions...

2021-05-18 09:22 UTC, nafur commented on src/parser/input_parser.h
> +  Command* nextCommand();
I suspect that the caller of `nextCommand()` owns the returned `Command`. If so, please make it a `std::unique_ptr`.

2021-05-18 09:22 UTC, nafur commented on src/parser/input_parser.cpp
> +    d_state->setDone(cmd == nullptr);
This feels like `d_state` should implement this logic itself. In particular, as the logic is repeated below.

2021-05-18 09:22 UTC, nafur commented on src/parser/parser.h
> +  InputLanguage d_lang;
Why do we suddenly need this information here? (i.e.: where did it live beforehand?)

2021-05-18 09:22 UTC, nafur commented on src/parser/parser.h
> +   * @param useMmap Whether to map the file.
```suggestion
   * @param useMmap Improve reading this file using `mmap`.
```

2021-05-18 09:22 UTC, nafur commented on src/parser/parser.h
> +  std::unique_ptr<InputParser> parseFile(const std::string& fname,
Are we going to adopt `std::filesystem`? This may be a good place to start... though maybe not in this PR.

2021-05-18 09:22 UTC, nafur commented on src/parser/parser.h
> +   * @param name The name of the stream (used for parser errors)
```suggestion
   * @param name The name of the stream (used for parser errors).
```

2021-05-18 09:22 UTC, nafur commented on src/parser/parser.h
> +   * @param name The name of the stream (used for parser errors)
```suggestion
   * @param name The name of the stream (used for parser errors).
```

2021-05-18 09:22 UTC, nafur commented on src/parser/parser.h
> +  Command* getNextCommand();
As for InputParser: should we return a unique_ptr here?

2022-11-21 14:10 UTC, ajreynol commented
An alternative implementation was introduced in https://github.com/cvc5/cvc5/pull/9276, closing this.

2022-11-21 14:10 UTC, closed without merging