More precise includes of `Node` constants
cvc5/cvc5 pull request #6617
Opened 2021-05-24 23:46 UTC by 4tXJ7f

We store constants, e.g., `BitVector` and `Rational`, in our node infrastructure. As a result, we were indirectly including some headers in almost all files, e.g., the GMP headers. This commit changes that by forward-declaring the classes for the constants. As a result, we have to include headers like `util/rational.h` explicitly when we use `Rational` but it saves about 3 minutes in compile time (CPU time).

The commit changes `RoundingMode` from an `enum` to an `enum class` such that it can be forward declared.

2021-05-25 03:08 UTC, mpreiner commented on src/preprocessing/passes/bv_to_int.h
> +#include "util/rational.h"
Rational doesn't seem to be used in this header, include shouldn't be needed here.

2021-05-25 07:09 UTC, nafur requested changes
A few minor comments.

2021-05-25 07:09 UTC, nafur commented on src/theory/bv/kinds
> +	BitVectorSize \
```suggestion
      struct \
	BitVectorSize \
```

2021-05-25 07:09 UTC, nafur commented on src/theory/bv/kinds
> +	BitVectorBitOf \
```suggestion
      struct \
	BitVectorBitOf \
```

2021-05-25 07:09 UTC, nafur commented on src/theory/bv/kinds
> +	BitVectorBitOf \
and more below...

2021-05-25 16:01 UTC, aniemetz commented on src/expr/type_node.cpp
> +
I agree, it would be good to change this in this PR.

2021-05-26 00:46 UTC, mpreiner approved these changes

2021-05-26 00:46 UTC, 4tXJ7f commented
Thanks for the comments. I have addressed them and updated my vim config to show me tabs as characters ;)

2021-05-26 06:09 UTC, nafur approved these changes
LGTM.

2021-05-26 14:30 UTC, merged