modular bv2int: Stubs and some implementations
cvc5/cvc5 pull request #6760
Opened 2021-06-17 21:20 UTC by yoni206

This PR adds the file `int_blaster.cpp`. Most of the functions are not yet implemented. Two main functions are implemented.
Additionally, code that will no longer be needed is removed from the BV rewriter.

2021-06-21 14:23 UTC, ajreynol requested changes

2021-06-21 14:23 UTC, ajreynol commented on src/theory/bv/int_blaster.cpp
> +/*********************                                                        */
I think this is the old header style, do update it.

2021-06-21 14:23 UTC, ajreynol commented on src/theory/bv/int_blaster.cpp
> +Node IntBlaster::makeBinary(Node n)
Does this method need to do a traversal?  Can't we just make this a "one step" method that is called as a first step of the intBlast traversal?  I.e. as intBlast traverses, we makeBinary the current node and then translate to int?

2021-06-22 06:23 UTC, yoni206 commented
Thanks for the comments! Addressed both of them.

2021-06-22 14:37 UTC, ajreynol requested changes
Thanks for eliminating the traversal, looks a lot nicer now.  A few last minor comments, else LGTM.

2021-06-22 14:37 UTC, ajreynol commented on src/theory/bv/int_blaster.cpp
> +      for (Node child : current)
```suggestion
      for (const Node& child : current)
```

2021-06-22 14:37 UTC, ajreynol commented on src/theory/bv/int_blaster.cpp
> +    d_binarizeCache[n] = result;
Remember to clang-format.

2021-06-22 18:56 UTC, ajreynol approved these changes

2021-06-22 19:11 UTC, merged