pow2: Adding monotonicity lemma
cvc5/cvc5 pull request #6793
Opened 2021-06-24 06:17 UTC by yoni206

We add the lemma x<=y --> pow2(x)<=pow2(y) to the pow2 solver.
Additionally, some renaming of variables is introduced for better clarity.

2021-06-24 14:54 UTC, ajreynol requested changes
You are using a quadratic algorithm that sends redundant lemmas :)  Do write this as using a sort algorithm; then the lemmas are linear.  i.e. pow2(t1) .... pow2(tn), sort by t1^M .... tn^M then only add n-1 lemmas C => pow2(t_i1) < pow2( t_i2 ) .... C => pow2( t_i{n-1}) < pow2( t_in ).

2021-06-24 19:56 UTC, ajreynol requested changes

2021-06-24 19:56 UTC, ajreynol commented on src/theory/arith/nl/pow2_solver.cpp
> +  NodeManager* nm = NodeManager::currentNM();
Can you move this to its own method?

2021-06-24 20:36 UTC, yoni206 commented on src/theory/arith/nl/pow2_solver.cpp
> +  NodeManager* nm = NodeManager::currentNM();
done

2021-06-24 20:53 UTC, ajreynol requested changes
Would be good to have a regression to test the code works already, or is this not possible yet?

2021-06-24 21:06 UTC, yoni206 commented
Regressions are 1 PR away, if that's ok with you

2021-06-25 02:34 UTC, ajreynol approved these changes

2021-06-25 03:09 UTC, merged