proofs: Properly track pre- and post-rewrites in bbAtom().
cvc5/cvc5 pull request #7147
Opened 2021-09-07 22:50 UTC by mpreiner

This commit refactors the proof bit-blaster to properly track the pre- and post-rewrites in bbAtom(). The individual bit-blast steps are recorded in a term conversion proof generator. The overall bit-blast proof is stored in a BitblastProofGenerator, which tracks the pre- and post-rewrite and includes the bit-blast proof of the TCPG.

2021-09-08 13:59 UTC, ajreynol requested changes
A few minor requests.

2021-09-08 13:59 UTC, ajreynol commented on src/theory/bv/bitblast/proof_bitblaster.h
> +/** Proof generator fot bit-blast proofs. */
I'd prefer if this was moved to its own file.

2021-09-08 13:59 UTC, ajreynol commented on src/theory/bv/bitblast/proof_bitblaster.h
> +  /** Record bit-blast step. */
Can you add some more documentation here about the arguments?

2021-09-08 20:09 UTC, HanielB requested changes

2021-09-08 20:09 UTC, HanielB commented on src/theory/bv/bitblast/proof_bitblaster.cpp
> +     */
add here a proof tree combining these three things

2021-09-08 20:09 UTC, HanielB commented on src/theory/bv/bitblast/proof_bitblaster.cpp
> +    cdp.addProof(d_tcpg->getProofFor(rwt.eqNode(bbt)));
when `rwt` is the same as `t` this is the statement that allows the return of this method to work properly. This is not very clear currently. Add to the beginning of this block, where you describe the proof being built, how it relates to what is stored in `cdp` and the final call in the method.

2021-09-08 20:09 UTC, HanielB commented on src/theory/bv/bitblast/proof_bitblaster.cpp
> +    if (transSteps.size() > 1)
reforce here that the `else` of this case is a no-op because `eq` will already have been justified above

2021-09-10 18:34 UTC, HanielB approved these changes
LGTM

2021-09-14 17:39 UTC, ajreynol approved these changes

2021-09-14 17:39 UTC, merged