Fix handling of conversions between FP and reals
cvc5/cvc5 pull request #7149
Opened 2021-09-08 09:31 UTC by 4tXJ7f

Fixes #7056. Currently, we introduce a UF for conversions between FP
numbers and reals. This is done as part of `ppRewrite()`. The problem is
that terms sent to `ppRewrite()` are not fully preprocessed yet and the
FP theory solver was storing terms that were not fully preprocessed in a
map for later lookup. For the issue at hand, the conversion term
contained an `ite`, which was later removed. As a result, the theory
solver did not consider the term to be relevant when refining
abstractions. This commit changes the handling of conversion functions
to instead adding purification lemmas for conversion terms when they are
registered. The purification lemmas are needed, because otherwise, we
can't retrieve the model values for the term without the rewriter
interferring.

2021-09-08 14:54 UTC, ajreynol requested changes

2021-09-08 16:06 UTC, 4tXJ7f commented on src/theory/fp/theory_fp.cpp
> +  (void)success;  // Only used for assertion
This is just moved from existing code but I'll update.

2021-09-08 16:31 UTC, 4tXJ7f commented on src/theory/fp/theory_fp.cpp
> +    handleLemma(node.eqNode(sk), InferenceId::FP_REGISTER_TERM);
This code is part of `registerTerm()`, which is called in `preRegisterTerm()` and `preNotifyFact()`, so I think that sending a lemma is correct, no?

2021-09-09 18:33 UTC, ajreynol commented on src/theory/fp/theory_fp.cpp
> +    handleLemma(node.eqNode(sk), InferenceId::FP_REGISTER_TERM);
Ah, in fact, you've moved it in this PR, right?  In this case, there is no issue.

2021-09-09 19:10 UTC, aniemetz reviewed
I think the comment on line 639 in `handleLemma` is obsolete with these changes.

2021-09-13 15:32 UTC, martin-cs approved these changes
Thanks to @4tXJ7f this one seems like it was a real challenge to find!  I /think/ I understand the fix; rather than creating new uninterpreted functions it uses Purify Skolem.  Otherwise the (static) lemmas it generates and the refinement are unchanged.

2021-09-14 19:48 UTC, ajreynol approved these changes

2021-09-21 00:10 UTC, merged