Turn kinds in python API into a proper Enum
cvc5/cvc5 pull request #7686
Opened 2021-11-23 20:20 UTC by nafur

2021-11-30 13:17 UTC, yoni206 approved these changes
LGTM, modulo minor comments inline.

2021-11-30 13:17 UTC, yoni206 commented on docs/ext/autoenum.py
> +    app.add_autodocumenter(EnumDocumenter)
```suggestion
    app.add_autodocumenter(EnumDocumenter)
    
```

2021-11-30 13:17 UTC, yoni206 commented on examples/api/python/id.py
> +from pycvc5 import Kind
Maybe this can even be deleted?

2021-11-30 13:17 UTC, yoni206 commented
added do-not-merge to allow a review from @aniemetz before merging.

2021-12-01 00:21 UTC, aniemetz requested changes

2021-12-01 00:21 UTC, aniemetz commented on docs/api/python/regular/python.rst
> +regular Python API
```suggestion
Regular Python API Documentation
```

2021-12-01 00:21 UTC, aniemetz commented on docs/api/python/python.rst
> +Python API
Should the visibility of the individual api toctrees really be hidden?
Also: `compatibility API` -> `Compatibility Python API` and `regular Python API` -> `Regular Python API`
Can you make the former change also for the header of the compat api page?

2021-12-08 02:53 UTC, aniemetz approved these changes

2021-12-08 04:16 UTC, merged