Add documentation for QuickStart.java
cvc5/cvc5 pull request #7730
Opened 2021-12-01 22:12 UTC by mudathirmahgoub

2021-12-01 22:59 UTC, nafur reviewed
Please follow the style of the other quickstarts and use `literal-include` instead of `code-block`.

2021-12-01 23:19 UTC, mudathirmahgoub commented
> Please follow the style of the other quickstarts and use `literal-include` instead of `code-block`.

I have a strong opinion against this.  `literal-include` is only reasonable if line numbers do not change, which is rare. 
It does not save any effort if they change, and is even worse when the change happens at the beginning of the file, where you need to update all blocks, compared to only one place with `code-block`. 
It is not flexible if you want to diverge from the original code as I did in this [line](https://github.com/cvc5/cvc5/pull/7730/files#diff-6e9db0b83ba3947096189ca5e6c4e5eff8bc0df1fb13abf2fe329296c00b490fR10).

2021-12-01 23:46 UTC, nafur commented
> > Please follow the style of the other quickstarts and use `literal-include` instead of `code-block`.
> 
> I have a strong opinion against this. `literal-include` is only reasonable if line numbers do not change, which is rare. It does not save any effort if they change, and is even worse when the change happens at the beginning of the file, where you need to update all blocks, compared to only one place with `code-block`. It is not flexible if you want to diverge from the original code as I did in this [line](https://github.com/cvc5/cvc5/pull/7730/files#diff-6e9db0b83ba3947096189ca5e6c4e5eff8bc0df1fb13abf2fe329296c00b490fR10).

I acknowledge your opinion, and you may very well include **additional** code blocks (like the one you mentioned). I agree that keeping the line numbers in sync can be an issue. However, keeping the code itself in sync is an issue as well.
I find both variants bad for different reasons.

At the end, though, we concluded that using line numbers is safer: outdated line numbers usually result in code that does obviously not match the description, while out-of-date code that was copied may have more subtle issues due to refactorings (which will never show up anywhere, until some user tries to copy code from the quickstart). I just did such a refactoring concerning the Kinds in the python API. Also, such an error is more likely to be "transparent" to a user (i.e. the user recognizes it as a simple error that he can workaround himself).

2021-12-01 23:50 UTC, aniemetz commented
I fully agree with @nafur. We have discussed this in the past and concluded that including code via line numbers is the way to go for reasons @nafur mentioned.

2021-12-02 06:26 UTC, mudathirmahgoub commented
Since it has already been decided, I updated the file to use line numbers. 
I guess we have to live with some aesthetics issues like the first block in the image below which results from the indented lines in the original file, unlike the second code block which is displayed as expected. 

![image](https://user-images.githubusercontent.com/22382000/144368708-df5fe90d-9d43-4ccd-a4ba-b90eeae03075.png)

2021-12-02 06:38 UTC, 4tXJ7f commented
For the quickstart examples, maybe we could also use a [literate programming extension](https://sphinx-litprog.readthedocs.io/en/stable/)?

2021-12-02 06:49 UTC, 4tXJ7f requested changes
Some minor requests and some suggestions.

2021-12-02 06:49 UTC, 4tXJ7f commented on docs/api/java/quickstart.rst
> +The simplest way to set a logic for the solver is to choose "ALL".
```suggestion
The simplest way to set a logic for the solver is to choose ``"ALL"``.
```

2021-12-02 06:49 UTC, 4tXJ7f commented on docs/api/java/quickstart.rst
> +First, create a cvc5 `Solver <io/github/cvc5/api/Solver.html>`_ instance using try with resources:
Nit: wrap line

2021-12-02 06:49 UTC, 4tXJ7f commented on docs/api/java/quickstart.rst
> +and for this we have to enable the following options.
```suggestion
To produce models and unsat cores, we have to enable the following options.
```

(I know that this is just copied from the other guides, but the wording is a bit verbose)

2021-12-02 06:49 UTC, 4tXJ7f commented on docs/api/java/quickstart.rst
> +In the following, we will define constraints of reals and integers.
```suggestion
In the following, we will define real and integer constraints.
```

2021-12-02 06:49 UTC, 4tXJ7f commented on docs/api/java/quickstart.rst
> +Notice that these are *symbolic* constants, but not actual values.
```suggestion
Notice that these are *symbolic* constants, not actual values.
```

2021-12-02 06:49 UTC, 4tXJ7f commented on docs/api/java/quickstart.rst
> +to the assertion command.
```suggestion
in the assertion command.
```

2021-12-02 08:26 UTC, mudathirmahgoub commented on docs/api/java/quickstart.rst
> +First, create a cvc5 `Solver <io/github/cvc5/api/Solver.html>`_ instance using try with resources:
Done

2021-12-02 20:19 UTC, 4tXJ7f commented on docs/api/java/java.rst
> +specifically, pairs of Java BigInteger objects, to represent rational numbers.
```suggestion
specifically, pairs of Java `BigInteger` objects, to represent rational numbers.
```

2021-12-02 20:51 UTC, nafur commented on docs/api/java/java.rst
> +
The quickstart does not show up in the menu. I'd suggest to add a hidden toc here:
```suggestion

.. toctree::
    :hidden:

    quickstart
    API documentation <index>
```

2021-12-02 21:23 UTC, nafur commented
> I guess we have to live with some aesthetics issues like the first block in the image below which results from the indented lines in the original file, unlike the second code block which is displayed as expected.

The `literalinclude` directive should support the `:dedent:` option (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-option-code-block-dedent). I see that this is more of an issue for java, as all relevant code is indented three times (class, method, try) while both python and c++ code is only indented once.

2021-12-02 21:31 UTC, mudathirmahgoub commented
> > I guess we have to live with some aesthetics issues like the first block in the image below which results from the indented lines in the original file, unlike the second code block which is displayed as expected.
> 
> The `literalinclude` directive should support the `:dedent:` option (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-option-code-block-dedent). I see that this is more of an issue for java, as all relevant code is indented three times (class, method, try) while both python and c++ code is only indented once.

I already tried this option yesterday, it did not work with `literalinclude`.

2021-12-02 21:37 UTC, nafur commented
> I already tried this option yesterday, it did not work with `literalinclude`.

Which sphinx version do you use? I found that the sphinx that comes from the ubuntu repositories is pretty old (in my case 3.5.4 vs. 4.3.0 from pip). It works on my machine with 4.3.0 and the following syntax (I tested on the python quickstart):
```
.. literalinclude:: ../../../../examples/api/python/quickstart.py
     :language: python
     :lines: 22
     :dedent: 2
```

2021-12-02 21:55 UTC, mudathirmahgoub commented
> 

Mine is installed with pip, 
```bash
pip install sphinx
Requirement already satisfied: sphinx in /home/mudathir/.local/lib/python3.8/site-packages (4.2.0)
```
This change does not work
```rst
.. literalinclude:: ../../../examples/api/java/QuickStart.java
     :language: java
     :lines: 160-166
     :dedent: 1
     ```

2021-12-02 22:12 UTC, mudathirmahgoub commented
I used the wrong value `:dedent:`.  6 seems to fix it. 
So not just you need to worry about line numbers, but you also need to figure out how many characters of the indentation. 
I am not a fan of `.. literalinclude::`.

2021-12-02 22:21 UTC, nafur reviewed
Ah I forgot about how sphinx integrates tocs into the overall tree. This moves it out of the "Building cvc5 Java API" section...

2021-12-02 22:21 UTC, nafur commented on docs/api/java/java.rst
> +
```suggestion

.. toctree::
    :hidden:

    quickstart
    API documentation <index>

```

2021-12-02 22:21 UTC, nafur commented on docs/api/java/java.rst
> +
```suggestion
```

2021-12-06 18:16 UTC, nafur approved these changes
Just a final suggestion. Thanks for all the changes!

2021-12-06 18:16 UTC, nafur commented on docs/api/java/quickstart.rst
> +    <examples>/api/java/QuickStart.java
Show the java code by default.
```suggestion
    <examples>/api/java/QuickStart.java
    <examples>/api/cpp/quickstart.cpp
```

2021-12-07 01:31 UTC, 4tXJ7f approved these changes
LGTM, thanks for the updates.

2021-12-07 01:31 UTC, merged