Integrate new int-blaster
cvc5/cvc5 pull request #7781
Opened 2021-12-09 19:44 UTC by yoni206

This PR removes the code that translates from bit-vectors to integers from the bv_to_int preprocessing pass, and replaces it with a call to the IntBlaster module.

Tests are updated and added, as well as other minor changes.

Solves the following issues (and contains corresponding tests):
https://github.com/cvc5/cvc5-projects/issues/345
https://github.com/cvc5/cvc5-projects/issues/344
https://github.com/cvc5/cvc5-projects/issues/343

@mpreiner FYI

2021-12-10 20:54 UTC, ajreynol requested changes

2021-12-10 20:54 UTC, ajreynol commented on src/preprocessing/passes/bv_to_int.cpp
> +    Node rwNode = Rewriter::rewrite(intNode);
```suggestion
    Node rwNode = rewrite(intNode);
```

2021-12-10 20:54 UTC, ajreynol commented on src/preprocessing/passes/bv_to_int.h
> +/*********************                                                        */
I believe this is the old style of headers, update this to the new header.

2021-12-12 06:52 UTC, yoni206 commented
Thanks, your comments were addressed here: 7413ab8.

2021-12-13 15:59 UTC, ajreynol approved these changes

2021-12-13 16:16 UTC, merged