Don't prune non-interval proof nodes in coverings proofs
cvc5/cvc5 pull request #8084
Opened 2022-02-09 16:40 UTC by nafur

We need to prune the proof nodes from a coverings proof in certain cases. To match the proof nodes with the coverings-internal intervals, we use ids, where non-interval nodes have the id zero. We somehow forgot to check for zero, ending up pruning all the nodes all the time and generating empty proofs. (Note that we do not know how to build a proper proof checker for these yet, so we didn't notice).
This PR fixes the issue, only pruning interval nodes.

2022-02-09 19:12 UTC, HanielB commented
How does this impact the non-linear proofs? Makes the solver generate less THEORY_LEMMA or something like that?

2022-02-09 19:17 UTC, nafur commented
> How does this impact the non-linear proofs? Makes the solver generate less THEORY_LEMMA or something like that?

It impacts non-linear proofs in the sense that it now generates meaningful proofs again. Right now, all proofs from the coverings solver simply infer `false` from nothing...

2022-02-09 19:24 UTC, HanielB commented
But the occurrences of `ARITH_NL_CAD_DIRECT` and `ARITH_NL_CAD_RECURSIVE` would be the same, just their content would change?

2022-02-09 19:34 UTC, nafur commented
> But the occurrences of `ARITH_NL_CAD_DIRECT` and `ARITH_NL_CAD_RECURSIVE` would be the same, just their content would change?

They now look like they were always supposed to look, and like they looked at some point in the past. Covering proofs are simply broken right now, most probably at least since #7470.

2022-02-15 23:43 UTC, ajreynol requested changes
One minor request, else LGTM

2022-02-15 23:43 UTC, ajreynol commented on test/unit/theory/theory_arith_cad_white.cpp
> +  //std::cout << *pg << std::endl;
Remove this.

2022-02-23 15:18 UTC, merged