Refactor documentation
cvc5/cvc5 pull request #8288
Opened 2022-03-11 02:01 UTC by nafur

This PR moves some stuff around in our documentation. Most notably, it moves some sections out of the "Binary documentation" to become their own top-level sections. While doing so, it refactors a few things in options and statistics to be more agnostic to the way cvc5 is used.

2022-03-11 02:03 UTC, nafur commented
I think this is mostly what we have discussed offline. Please have a look and let me know what should still be changed. The updated documentation should be available at https://cvc5.github.io/docs-ci/docs-pr8288/ shortly after the CI is done with this PR...

2022-03-17 16:54 UTC, 4tXJ7f requested changes
Thanks for doing this. Just some minor comments.

2022-03-17 16:54 UTC, 4tXJ7f commented on docs/binary/binary.rst
> +interface, but cvc5 also supports other input languages:
```suggestion
interface.

The cvc5 binary supports the following input languages:
```

The "but ... also" sounds a bit weird in the original sentence.

2022-03-21 20:24 UTC, 4tXJ7f approved these changes
LGTM

2022-03-21 21:19 UTC, merged