Cppapi
cvc5/cvc5 pull request #8425
Opened 2022-03-28 20:48 UTC by aniemetz

2022-03-28 20:56 UTC, 4tXJ7f reviewed
Should this method be marked experimental?

2022-03-28 22:05 UTC, aniemetz commented
> Should this method be marked experimental?

Actually, no. And `Sort::instantiate` shouldn't either. I have included that fix in this PR.

2022-03-29 00:08 UTC, ajreynol requested changes
A few minor comments else LGTM

2022-03-29 00:08 UTC, ajreynol commented on src/api/cpp/cvc5.h
> +   * Is this an instantiated (parametric datatype or unintpreted sort
```suggestion
   * Is this an instantiated (parametric datatype or uninterpreted sort
```

2022-03-29 00:08 UTC, ajreynol commented on src/api/cpp/cvc5.h
> +   * instantiating sort parameters of a parametric sort with sort arguments
```suggestion
   * instantiating a sort with sort arguments
```

2022-03-29 00:08 UTC, ajreynol commented on src/api/cpp/cvc5.h
> +   * instantiating sort parameters of a parametric sort with sort arguments
Technically the uninterpreted sort constructor doesn't have parameters.

2022-03-29 00:51 UTC, ajreynol approved these changes

2022-03-29 01:37 UTC, merged