Add operators table.aggr and table.join
cvc5/cvc5 pull request #8681
Opened 2022-04-29 05:41 UTC by mudathirmahgoub

2022-05-03 20:18 UTC, ajreynol requested changes
The reduction for TABLE_AGGREGATE should be made available in the rewriter, otherwise I don't think we are evaluating TABLE_AGGREGATE yet, right?

2022-05-03 20:18 UTC, ajreynol commented on src/api/cpp/cvc5_kind.h
> +  TABLE_AGGREGATE,
Need documentation here.

2022-05-03 20:52 UTC, mudathirmahgoub commented
> The reduction for TABLE_AGGREGATE should be made available in the rewriter, otherwise I don't think we are evaluating TABLE_AGGREGATE yet, right?

In prewriting, Table_AGGREGATE is reduced using bag.partition operator (which would be better to reduce it using table.group) during preprocessing 
https://github.com/cvc5/cvc5/pull/8681/files#diff-baf1cbe358ed5c34628c6afdfc771eb4fab401c8bd98b4504f6ac3c3ed651ce4R109
. So the rewriter would not see it, but it would be evaluated

2022-05-04 21:08 UTC, mudathirmahgoub commented on src/api/cpp/cvc5_kind.h
> +  TABLE_AGGREGATE,
Done.

2022-05-04 21:28 UTC, ajreynol requested changes
One minor request else LGTM

2022-05-04 21:28 UTC, ajreynol commented on src/theory/bags/bag_reduction.h
> +  static Node reduceAggregateOperator(Node node);
Add a quick doc here.

2022-05-04 21:49 UTC, mudathirmahgoub commented on src/theory/bags/bag_reduction.h
> +  static Node reduceAggregateOperator(Node node);
Done

2022-05-05 01:09 UTC, ajreynol approved these changes

2022-05-05 13:41 UTC, merged