fix gtest installation on m1
cvc5/cvc5 pull request #8813
Opened 2022-05-23 20:58 UTC by yoni206

When trying to build unit tests on m1 mac an error about deprecated methods fails the compilation of gtest.
This PR suppresses these checks on a mac, which makes the installation of gtest work smoothly.

2022-05-24 20:47 UTC, nafur commented on cmake/FindGTest.cmake
> +	  -DCMAKE_CXX_FLAGS=${CARGS}
```suggestion
	      -DCMAKE_CXX_FLAGS=${CARGS}
```

2022-05-25 16:13 UTC, mpreiner commented
@yoni206 What's the error message you get when trying to compile googletest?

2022-05-25 19:51 UTC, yoni206 commented
@mpreiner 
It was several `error: definition of implicit copy constructor` errors. Full log here:

[tmp.txt](https://github.com/cvc5/cvc5/files/8774135/tmp.txt)

2022-05-25 20:21 UTC, nafur commented
I wonder whether we should generally suppress the warnings, or make it more specific (to only suppress on M1, not for macOS in general)

2022-05-25 21:26 UTC, yoni206 commented
I suggest only on M!. pushed.

2022-05-25 23:16 UTC, 4tXJ7f requested changes

2022-05-25 23:16 UTC, 4tXJ7f commented on cmake/FindGTest.cmake
> +      set(CARGS -w)
Let's only disable the specific warning that causes troubles and add a comment about why we are disabling that warning (if there is an issue on their issue tracker, we should link to it).

2022-05-31 07:53 UTC, yoni206 commented
@mpreiner thanks. That's a much better solution, and it works. [ad5ee52](https://github.com/cvc5/cvc5/pull/8813/commits/ad5ee5250f65c7c565c4de3a695e0af64be6fb18)

2022-05-31 15:46 UTC, 4tXJ7f approved these changes
LGTM

2022-05-31 15:47 UTC, merged