[proof] [cnf] Track input and lemma clauses in ProofCnfStream
cvc5/cvc5 pull request #8993
Opened 2022-07-22 21:27 UTC by HanielB

This will be useful for producing proof components.

2022-07-22 21:28 UTC, ajreynol requested changes

2022-07-22 21:28 UTC, ajreynol commented on src/prop/proof_cnf_stream.h
> +   * @param input whether the SAT solver can choose to remove the clauses
Fix doc.

2022-07-22 21:28 UTC, HanielB commented on src/prop/proof_cnf_stream.h
> +   * @param input whether the SAT solver can choose to remove the clauses
had just noticed :)

2022-07-24 23:26 UTC, ajreynol approved these changes

2022-07-25 14:43 UTC, merged