Univariate root finding
cvc5/cvc5 pull request #9115
Opened 2022-09-05 18:08 UTC by alex-ozdemir

2022-09-13 08:34 UTC, alex-ozdemir commented on src/theory/ff/roots.cpp
> +// sorting based on strings because CoCoA doesn't cmp
Yes, that's a natural question. Unfortunately, comparison only works for elements of 'ordered' rings: i.e., a ring `R` for which `CoCoA::IsOrderedDomain(R)` returns true. Most rings that CoCoA implements do not satisfy this, including prime fields.

I've expanded the comment a bit.

2022-09-14 11:46 UTC, alex-ozdemir commented
Following up on our discussion, the global manager must be created *exactly* once.

Creating it multiple times does cause an error.

2022-09-27 14:59 UTC, ajreynol requested changes
Just a request to doc the singleton pointer.

2022-09-27 19:53 UTC, alex-ozdemir commented on src/util/cocoa_globals.h
> +extern CoCoA::GlobalManager* s_cocoaGlobalManager;
Yep! Just did it. I put most of the documentation at the top of the header.

2022-09-27 20:39 UTC, ajreynol approved these changes
LGTM

2022-09-29 15:31 UTC, merged