Docs for installing python API in M1
cvc5/cvc5 pull request #9176
Opened 2022-09-29 08:29 UTC by yoni206

Adds documentation instructions for the python API on M1 MacOS.

2022-09-29 08:30 UTC, yoni206 commented
@barrettcw FYI.

2022-10-01 19:14 UTC, 4tXJ7f requested changes
Thank you for doing this. Some minor suggestions.

2022-10-01 19:14 UTC, 4tXJ7f commented on docs/api/python/python.rst
> +------------
```suggestion
Installation (ARM64 variants of Linux and macOS)
------------
```

2022-10-01 19:14 UTC, 4tXJ7f commented on docs/api/python/python.rst
> +Installation (Except MacOS with Apple Silicon)
```suggestion
Installation (x86-64 variants of Linux and macOS)
```
The instructions don't work for Windows or ARM versions of Linux, so it is better to explicitly list what's supported.

2022-10-01 19:14 UTC, 4tXJ7f commented on docs/api/python/python.rst
> +For M1 Macs, the base and pythonic Python API can be installed from source as follows:
```suggestion
For ARM64-based machines (including Apple computers with M1 and M2 chips), the base and the pythonic Python API can be installed from source as follows:
```

2022-10-02 07:03 UTC, yoni206 commented
Thanks for your suggestions! I have committed them.

2022-10-03 03:45 UTC, 4tXJ7f approved these changes
LGTM

2022-10-13 15:32 UTC, merged