Separate propagation and lemma phase in core strings solver
cvc5/cvc5 pull request #9372
Opened 2022-12-21 22:20 UTC by ajreynol

This will allow further extensions to the strategy for steps that should go between these two phases.  These two phases are run back-to-back, hence there should be no behavior changes in this PR.

Also makes some minor changes to InferInfo in preparation for making side effect processing more consistent.

2022-12-26 09:06 UTC, yoni206 approved these changes

2022-12-26 18:03 UTC, 4tXJ7f requested changes
Some minor requests.

2023-01-03 21:32 UTC, ajreynol commented on src/theory/strings/core_solver.h
> +   * are sent to the inference manager only when checkNormalFormsEq is called.
I'll mention this (as part of (C)).

2023-01-04 15:18 UTC, 4tXJ7f approved these changes
LGTM, thanks for the updates!

2023-01-05 22:35 UTC, merged