ff: Filter duplicate registrations in subtheory.
cvc5/cvc5 pull request #9438
Opened 2023-01-20 17:34 UTC by alex-ozdemir

2023-01-20 18:33 UTC, ajreynol requested changes
Thanks, this makes sense now.  The proper fix is actually to make `d_leaves` *SAT* context dependent instead of user context dependent. 
Preregistration already ensures terms are registered at most once in a SAT context, so a set is not necessary.  

Thus the fix should just be one line change.

2023-01-20 18:34 UTC, ajreynol commented on src/theory/ff/sub_theory.cpp
>        d_leaves(userContext()),
```suggestion
      d_leaves(context()),
```

2023-01-21 18:36 UTC, ajreynol commented
This isn't a blocker for me at the moment, how about we revisit this when its convenient for you.  For now, we can leave the PR open.

2023-02-07 18:31 UTC, alex-ozdemir commented
I'm closing this in favor of #9486.

2023-02-07 18:31 UTC, closed without merging