Ensure notifications for all options changes in set defaults
cvc5/cvc5 pull request #9460
Opened 2023-01-25 14:50 UTC by ajreynol

This ensures that all changes to options in SetDefaults are notified in a uniform way.

The PR makes minor changes to defaults (e.g. the UF symmetry breaker is always auto-configured, but rarely is true, thus its default value is changed).  It also changes the logic slightly concerning when we notify when options changes.  We now notify whenever an option is changed (at verbosity=1), regardless of whether the change conflicts with a user option change.

This helps document the auto-configuration behavior of cvc5 for the user.

2023-02-13 19:57 UTC, aniemetz requested changes
We should introduce a wrapper to notify and modify the option, so that typos can be avoided and it is ensured that when we change the value of an option, notify is called.

2023-02-13 20:00 UTC, ajreynol commented
This would have to be further auto-generated code in the options object I believe, since we are calling the auto-generated methods to modify the options.  Do you think we should do this?

2023-02-17 17:49 UTC, aniemetz commented
Do we only want to notify in set_defaults?

2023-02-17 18:51 UTC, ajreynol commented
Yes.  

The intention is for all internal changes to options to occur in `set_defaults.cpp`, and for the output to reflect only what the set defaults module is doing.  User changes (e.g. via set-option) should not be notified.

2023-07-26 19:19 UTC, aniemetz approved these changes
Some minor things, else LGTM.

2023-07-26 19:19 UTC, aniemetz commented on src/smt/set_defaults.cpp
> + * concrete (e.g. is stored in a variable).
```suggestion
 * concrete (i.e., stored in a variable).
```

2023-07-26 19:19 UTC, aniemetz commented on src/smt/set_defaults.cpp
> + * Set domain.optName to value due to reason. Notify if value changes.
```suggestion
 * Set domain.optName to value due to reason. Notify if value changes.
 * Note this macro should be used if the value is concrete.
```

2023-07-26 19:19 UTC, aniemetz commented on src/smt/set_defaults.cpp
> + * Print the value using a stringstream conversion.
I think you can remove this line.

2023-07-26 19:19 UTC, aniemetz commented on src/smt/set_defaults.cpp
> + * by the user. Notify if value changes.
```suggestion
 * by the user. Notify if value changes.
 * Note this macro should be used if the value is concrete.
```

2023-07-26 19:19 UTC, aniemetz commented on src/smt/set_defaults.cpp
> + * conversion.
I think the last sentence can be removed. Add a note similarly to the one for `SET_AND_NOTIFY_VAL_SYM`.

2023-07-26 22:06 UTC, merged