Rcons
cvc5/cvc5 pull request #9781
Opened 2023-05-30 06:20 UTC by abdoo8080

2023-05-30 14:15 UTC, ajreynol requested changes
Does this also change the default weight on identity functions to 0?  If so, can you add a regression from circuit synthesis that is now solved fast?

Also, CI fails due to a java issue it looks like.

2023-06-06 13:30 UTC, ajreynol requested changes
Can you add the PR description what the changes are?

Also, I believe there is a change concerning the weights of identity functions but I couldn't spot where this change was.  Can you make sure this is documented?

2023-06-06 13:30 UTC, ajreynol commented on src/expr/sygus_grammar.cpp
> +void SygusGrammar::addRule(const Node& ntSym, const Node& rule)
Add an assertion that `ntSym` is in d_sdts.

(This is checked at the API but I foresee new internal usages of this class, in which case we should be sure this is called correctly).

2023-06-06 13:30 UTC, ajreynol commented on src/expr/sygus_grammar.cpp
> +  return static_cast<printer::smt2::Smt2Printer*>(Printer::getPrinter(ss))
You don't need to access the printer, I believe you can just invoke the static method here, i.e. `print::smt2::Smt2Printer::sygusGrammarString(..)`

2023-06-06 13:30 UTC, ajreynol commented on src/theory/quantifiers/sygus/sygus_reconstruct.cpp
> +  if (expr::match(convert(rewrite(datatypes::utils::sygusToBuiltin(sz))), convert(t), matches))
Can you move this line to its own method?  And perhaps separate it out into multiple lines.

(We will want to experiment with using single invocation subcalls as a replacement).

2023-06-06 16:06 UTC, abdoo8080 commented on src/expr/sygus_grammar.cpp
> +  d_sdts.at(ntSym).addConstructor(op, ss.str(), cargs, isId(op) ? 0 : -1);
The weight assigned to the identity rule is mentioned here.

2023-06-06 19:02 UTC, ajreynol approved these changes

2023-06-06 19:24 UTC, merged