Add DSL rewrite rule reconstruction algorithm
cvc5/cvc5 pull request #9782
Opened 2023-05-30 14:12 UTC by ajreynol

2023-11-15 23:18 UTC, mpreiner requested changes

2023-11-15 23:18 UTC, mpreiner commented on src/rewriter/rewrite_db_proof_cons.cpp
> +      parent[n] = curr;
```suggestion
      auto [it, inserted] = parent.emplace(n, curr);
      if (inserted)
      {
        toVisit.emplace_back(n);
      }
```

Saves again 1 map lookup.

2023-11-15 23:18 UTC, mpreiner commented on src/rewriter/rewrite_db_proof_cons.cpp
> +    for (size_t i = 0, size = steps.size(); i < size; i++)
```suggestion
    for (size_t i = 0, size = steps.size(); i < size; ++i)
```

2023-11-15 23:18 UTC, mpreiner commented on src/rewriter/rewrite_db_proof_cons.cpp
> +    pi->d_vars = pic.d_vars;
Maybe use std::move() here instead of copying the vector, since `pic.d_vars` will not be used anymore afterwards.

2023-11-22 09:43 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.cpp
> +      d_currStepLimit = stepLimit;
`stepLimit` is an input to this method, so we are setting a resource limit in this class concerning how many steps are allowed during this method.

2023-11-22 10:00 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.cpp
> +  d_currRecLimit++;
`getMatches` will make a recursive call for solving the current goal, so d_currRecLimit should be decremented prior to running it.

2023-11-22 10:04 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.cpp
> +    res = context[1].substitute(TNode(context[0][0]), TNode(conc[1]));
This needs explicit conversion.

2023-11-22 10:05 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.h
> +  uint32_t d_currStepLimit;
Yes I'll change.

2023-12-21 15:26 UTC, ajreynol commented on src/options/proof_options.toml
> +  type       = "int64_t"
Done

2023-12-21 15:27 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.cpp
> +  d_evalCache.clear();
Fixed

2023-12-21 15:27 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.cpp
> +            pfArgs[cur].insert(pfArgs[cur].end(), rsubs.begin(), rsubs.end());
Done

2023-12-21 15:27 UTC, ajreynol commented on src/rewriter/rewrite_db_proof_cons.cpp
> +  }
Done

2023-12-21 15:30 UTC, ajreynol commented
Concerning adding a constructor to `ProvenInfo`.  The issue is that `ProvenInfo` is often constructed/updated multiple times.
For example, a rewrite may fail at a particular recursion depth, but then succeed at a larger depth. Thus, its clearer in my opinion to just update its fields instead of worrying about two cases (new vs. updated).

2024-02-20 20:41 UTC, mpreiner commented on src/rewriter/rewrite_db_proof_cons.h
> +   * @param stepLimit The step limit for this call.
what does @return do?

2024-02-20 20:41 UTC, mpreiner commented on src/rewriter/rewrite_db_proof_cons.h
> +  static size_t d_fixedPointLimit;
```suggestion
  static size_t s_fixedPointLimit;
```
Should have s_ prefix since it's static.

2024-02-20 20:41 UTC, mpreiner commented on src/rewriter/rewrite_db_proof_cons.cpp
> +size_t RewriteDbProofCons::d_fixedPointLimit = 1000;
```suggestion
size_t RewriteDbProofCons::s_fixedPointLimit = 1000;
```

2024-02-21 17:13 UTC, mpreiner approved these changes

2024-02-21 19:37 UTC, merged