Add API for Proofs
cvc5/cvc5 pull request #9895
Opened 2023-07-12 22:22 UTC by hansjoergschurr

This pull requests adds support to get Proofs as proper objects from the API.

To do so it adds an object `Proof` that encapsulates a `ProofNode`.  Furthermore, it adds a function `proofsToString` to the `Solver` object that prints (a vector of) proofs.  Finally, it modifies the `getProof` function of the `Solver` object to return proofs.

Proof rules are returned as strings.

One thing I don't quite like is that the proof component configuration must be given to both the `getProof` and `proofsToString` method and must be the same.

2023-07-14 15:24 UTC, ajreynol requested changes
Generally looks good, just some minor comments.

2023-07-14 15:24 UTC, ajreynol commented on src/api/java/jni/proof.cpp
> + *   Mudathir Mohamed, Andres Noetzli, Andrew Reynolds
Update

2023-07-14 15:24 UTC, ajreynol commented on src/parser/api/cpp/command.cpp
> +    if (d_component != modes::PROOF_COMPONENT_FULL)
Enclose the body of the `if` in braces `{}`.

2023-07-14 15:24 UTC, ajreynol commented on test/unit/api/python/test_proof.py
> +# Unit tests for sort API.
```suggestion
# Unit tests for proof API.
```

2023-07-14 15:24 UTC, ajreynol commented on test/unit/api/python/test_proof.py
> +#   Yoni Zohar, Aina Niemetz, Makai Mann
Update

2023-07-14 15:24 UTC, ajreynol commented on src/smt/solver_engine.cpp
> +  this->getPfManager()->printProof(out, fp, format_mode);
```suggestion
  d_pfManager->printProof(out, fp, format_mode);
```

2023-07-14 15:24 UTC, ajreynol commented on src/smt/solver_engine.cpp
> +      this->getOptions().proof.proofFormatMode;
```suggestion
      getOptions().proof.proofFormatMode;
```

2023-07-14 15:24 UTC, ajreynol commented on test/unit/api/cpp/proof_black.cpp
> + *   Aina Niemetz, Andrew Reynolds, Alex Ozdemir
Update

2023-07-14 15:24 UTC, ajreynol commented on test/unit/api/java/ProofTest.java
> + *   Mudathir Mohamed, Aina Niemetz, Andrew Reynolds
Update

2023-08-14 16:44 UTC, aniemetz submitted a review, later dismissed

2023-08-14 16:44 UTC, aniemetz commented on include/cvc5/cvc5.h
> +   * @return A vector of proof nodes.
A `Proof` is not a `node`, is it? We don't really have a notion of `node` on the API level.

2023-08-14 16:44 UTC, aniemetz commented on include/cvc5/cvc5_types.h
> +enum ProofFormat
Just a reminder that this will have to change when #9915 is merged back. The enum values don't have to be prefixed with `PROOF_FORMAT` then either.

2023-08-14 16:44 UTC, aniemetz commented on src/api/cpp/cvc5.cpp
> +  return pf >= 0 && pf <= modes::PROOF_FORMAT_DEFAULT;
It seems that this function will become obsolete with #9915.

2023-08-14 16:44 UTC, aniemetz commented on src/api/cpp/cvc5.cpp
> +  for (std::shared_ptr<internal::ProofNode> p : proof_nodes)
This creates a shared_ptr per proof_node, why not use `auto&` to avoid such gotchas?

2023-10-12 14:20 UTC, ajreynol approved these changes
LGTM, thanks a lot for adding this.

2023-10-12 17:05 UTC, merged