c api: Introduce C/C++ specific handling of public enums.
cvc5/cvc5 pull request #9915
Opened 2023-07-25 19:18 UTC by aniemetz

This introduces a general way to use public enums both in the C++ and the (upcoming) C API. For the C++ case, we now use enum classes rather than enums for public enums. This also includes definitions for C API to_string conversions for public enums. C API definitions in cvc5_types.h are only included from the C API, guarded via a macro (thus, for now, not included yet when the header is included).

2023-08-07 15:55 UTC, ajreynol commented
As I understand it, the C++ API now uses enum classes? If so, we should take this opportunity to remove spurious common prefixes from the names of the enums, in `LearnedLitType`, `ProofComponent`, `FindSynthTarget`.

2023-08-07 17:53 UTC, aniemetz commented
> As I understand it, the C++ API now uses enum classes? If so, we should take this opportunity to remove spurious common prefixes from the names of the enums, in `LearnedLitType`, `ProofComponent`, `FindSynthTarget`.

Yes, that's right. And good point. I will make these changes.

2023-08-11 16:28 UTC, ajreynol approved these changes
Since this is a major change to the user (in particular requiring Kind::), I assume we should prioritize pushing for a 1.1 release soon?

2023-08-11 16:28 UTC, ajreynol commented on NEWS.md
> +  * SMT-LIB: New commands `find-synth` and `find-synth-next` which invoke the
Also change the bullet on line 25.

2023-08-14 16:31 UTC, mpreiner commented on include/cvc5/cvc5_types.h
> +#endif
```suggestion
#ifdef CVC5_API_USE_C_ENUMS
#ifndef CVC5__API__CVC5_C_TYPES_H
#define CVC5__API__CVC5_C_TYPES_H
#endif
#else
#ifndef CVC5__API__CVC5_CPP_TYPES_H
#define CVC5__API__CVC5_CPP_TYPES_H
#endif
#endif
```

2023-08-14 16:33 UTC, mpreiner commented on include/cvc5/cvc5_kind.h
> +#endif
```suggestion
#ifdef CVC5_API_USE_C_ENUMS
#ifndef CVC5__API__CVC5_C_KIND_H
#define CVC5__API__CVC5_C_KIND_H
#endif
#else
#ifndef CVC5__API__CVC5_CPP_KIND_H
#define CVC5__API__CVC5_CPP_KIND_H
#endif
#endif
```

2023-08-14 16:36 UTC, mpreiner commented
We should only merge this after we did a patch release.

2023-08-18 20:28 UTC, ajreynol requested changes

2023-08-18 20:28 UTC, ajreynol commented on NEWS.md
>      (`FIND_SYNTH_TARGET_ENUM`), or as a way of finding other terms of interest,
```suggestion
    (`FindSynthTarget::ENUM`), or as a way of finding other terms of interest,
```

2023-08-18 20:28 UTC, ajreynol commented on NEWS.md
>      (`FIND_SYNTH_TARGET_REWRITE_INPUT`).
```suggestion
    (`FindSynthTarget::REWRITE_INPUT`).
```

2023-08-21 17:20 UTC, ajreynol approved these changes

2023-08-22 18:17 UTC, merged