Make Proof Rule enum a part of the API
cvc5/cvc5 pull request #9925
Opened 2023-08-01 22:42 UTC by hansjoergschurr

This pull requests makes the enum that lists all proof rules a part of the API.

It also renames the enum from `PfRule` to `ProofRule`.  It also renames some unrelated types and function names that share the `PfRule` name (such as `DslPfRule`).
This rename unfortunately touches many files since `PfRule` is not an uncommon type.  (second to last commit)

I also added the enum to the Java and Python API, but I am not sure I got this right.  It is in the last commit.

2023-09-18 23:29 UTC, aniemetz commented on docs/api/java/CMakeLists.txt
> +  set(JAVADOC_MATHJAX [=["
How robust is this wrt to future Javadoc and Mathjax versions?

2023-09-18 23:29 UTC, aniemetz commented on include/cvc5/cvc5_proof_rule.h
> + * e.g. calling Rewriter::rewrite.
```suggestion
 * e.g., calling Rewriter::rewrite.
```

2023-09-21 23:50 UTC, aniemetz approved these changes

2023-09-24 15:08 UTC, ajreynol requested changes
A few requests.  Also, I believe you will need to add the print function for ProofRule to the unit tests here:
https://github.com/cvc5/cvc5/blob/main/test/unit/api/python/test_uncovered.cpp
https://github.com/cvc5/cvc5/blob/main/test/unit/api/java/UncoveredTest.cpp


Also a cpp unit test for printing proof rules needs to be added I think, similar to: 
https://github.com/cvc5/cvc5/blob/main/test/unit/api/cpp/api_kind_black.cpp

2023-09-24 15:08 UTC, ajreynol commented on include/cvc5/cvc5_proof_rule.h
> +typedef enum ENUM(Kind) ENUM(Kind);
Should say ProofRule not Kind?

2023-09-24 15:08 UTC, ajreynol commented on include/cvc5/cvc5_proof_rule.h
> +struct ProofRuleHashFunction
For consistency, perhaps this should change to the style for the hash function used by Kinds here: https://github.com/cvc5/cvc5/blob/main/include/cvc5/cvc5_kind.h#L5676.

(This code is using the standard practice for internal enums, but now that it is external maybe it should follow that one).

2023-09-27 00:17 UTC, ajreynol approved these changes

2023-09-27 00:58 UTC, merged